### ISSUE TITLE
As a event organizer, I want schedule news posts, so that I can send them at specific times without doing so manually

### ISSUE THREAD

**Issue by Krysset** [cthit/chalmers.it#23] opened 2023-12-01 14:38 UTC
### Description

Being able to schedule news posts would help event organizer being precise in their ticket releases, forms or help other time sensitive news posts be delivered on time. It would also help late night workers to post at a reasonable time, reduce the risk of forgetting to post news cause you otherwise would have to wait until the right time.

### Definition of Done

- [ ] An interface to set a time for the news post the be published
- [ ] Save the date and time that the nes post is to be published
- [ ] Publish the news post at the specific time

**Comment by GAsplund** [comment] 2023-12-01 14:43
Thanks for the issue! Unfortunately, this is a duplicate of #7 (However, I find the description here to be more clear)

**Closed as completed** 2024-03-11 12:02 UTC
Labels: suggestion
